### ISSUE TITLE
#define uint clashes with types.h in Mac OSX.

### ISSUE THREAD

**Issue by ahbarnett** [zgimbutas/mwrap#3]
Dear Zydrunas,
I realized this is an mwrap not finufft issue - but give some data and initial ideas in finufft issue #109.
(Sorry I'm on a Mac so can't figure out how to paste the url to that issue... :)
Best wishes, Alex

**Comment by zgimbutas** [comment]
Alex,

Incompatible C/C++ standards are fighting back again.  I deleted all
definitions of ulong, uint, ushort, uchar, etc. from mwrap-support.c. These
are now assumed to be defined natively by the compiler, and the copiers are
defined only if the corresponding types are detected during definition
parsing.  We did the same workaround to handle uint64_t, int64_t, uint32_t
and int32_t types.

The change did break old testing code test_transfers.mw, using gcc 7.5.0,
but it was trivially fixed by including 'typedef unsigned char uchar;' in
test_transfers.mw.

Please give the new update a try, it is in the main master branch.

Best, Zydrunas

**Comment by ahbarnett** [comment]
Wow, that was fast! It fixed the problem in the finufft mac octave - thanks!
And all the octave test_all.m still work for me on linux (gcc 7.5.0, octave 4.2.2.)
The only tests that don't compile are because of weird minus signs starting the commands in l. 28, 32 of here:
https://github.com/zgimbutas/mwrap/blob/master/testing/Makefile
Are those typos or deliberate?
Thanks again, Alex

**Comment by zgimbutas** [comment]
You are welcome! The tests that don’t compile are intentional. David created them to test error processing. -Zydrunas
